# Generated by Django 5.2.7 on 2025-12-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_suscripcion_id_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
