# Generated by Django 5.2.7 on 2025-12-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_gasto_eliminado_ingreso_eliminado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authusuario',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
